### ISSUE TITLE
user story

### ISSUE THREAD

**Issue by shaojunda** [xingrowth/nongsuoshu#1]
# 用户
1.  作为未付费用户可以查看免费浓缩书。rebecca
2.  作为未付费用户可以购买会员。(xdite)
3.  作为付费用户可以阅读全部的浓缩书。shaojunda
4.  作为付费用户可以查看会员期限。rebecca
5.  作为用户可以注册登录（手机注册）。rebecca
6.  作为用户可以根据关键词搜索浓缩书。shaojunda
7.  作为用户可以根据分类查看浓缩书。shaojunda
8.  作为用户可以修改自己的信息（密码、头像）rebecca
9.  已登录用户可以查看消息。shaojunda
# 管理员
1. 作为管理员可以上架浓缩书。liber
2. 作为管理员可以下架浓缩书。liber
3. 作为管理员可以编辑浓缩书。liber
4. 作为管理员可以删除浓缩书。liber
5. 作为管理员可以管理用户（升级为付费用户）。李教授
6. 作为管理员可以管理分类（创建、修改）。

关于我们 李教授

**Comment by rebecca9201** [comment]
could have：
1. 作为付费/未付费用户，可以分享浓缩书至微博，微信。
2. 作为未付费用户，可以查看付费浓缩书前100字。
3. 作为用户，付费后收到通知邮件。
4. 作为付费用户，每周收到包含最新浓缩书的推送的邮件。

**Comment by rebecca9201** [comment]
should have
作为付费/未付费用户，可以前台收藏浓缩书，后台查看已经收藏的浓缩书。
