### ISSUE TITLE
book show html

### ISSUE THREAD

**Issue by shaojunda** [xingrowth/nongsuoshu#4]
http://localhost:3000/books/58b81016-b180-468b-8bb7-c0ee9e7c1fce

图书的内容有 html 标签，如果才能渲染过来？ @xdite

**Comment by chpwang** [comment]
能否先用 html_safe 转？因为这些内容是管理员输入的，所以应该不怕 html_safe 的安全性问题。我去试一试。

**Comment by shaojunda** [comment]
html_safe 不起作用。 @chpwang

**Comment by chpwang** [comment]
稍等我去试一试，采用我们 hackschool 项目的方法看看 @shaojunda

**Comment by chpwang** [comment]
@shaojunda 我搞定了，等会儿测试完成拉 Pull Request

**Comment by shaojunda** [comment]
@chpwang 👌

**Comment by chpwang** [comment]
@xdite 已在 commit a024a1ba057a3c1e953cdbf7b12522ccf8acf3cd 解决
使用  `(CGI::unescapeHTML @resource.content).html_safe` 做两次 decoding
参考
http://stackoverflow.com/questions/22294153/rails-html-safe-not-escaping-html

PS:
我推荐使用的是：
sanitize(CGI::unescapeHTML book.content)
